# Generated by Django 3.0.2 on 2021-03-27 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursespecialist',
            name='photo',
            field=models.ImageField(default='defo', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 16, 28, 7, 570701)),
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 16, 28, 7, 570701)),
        ),
    ]
