# Generated by Django 3.0.2 on 2021-03-27 08:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_auto_20210327_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.CourseSpecialist'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 17, 2, 24, 116963)),
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 17, 2, 24, 116963)),
        ),
    ]
