# Generated by Django 3.0.2 on 2021-03-29 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_auto_20210327_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerstudent',
            name='question',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 18, 23, 45, 801908)),
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 18, 23, 45, 802909)),
        ),
    ]
