# Generated by Django 3.1.7 on 2021-04-01 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_auto_20210331_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursequestion',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='coursequestion',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursequestion',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 11, 45, 56, 360734)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 11, 45, 56, 358734)),
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 11, 45, 56, 359734)),
        ),
    ]
