# Generated by Django 3.1.7 on 2021-04-02 11:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpage', '0010_auto_20210401_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='coursequestion',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 20, 22, 18, 983509)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 20, 22, 18, 982478)),
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 20, 22, 18, 983509)),
        ),
        migrations.AlterUniqueTogether(
            name='registerstudent',
            unique_together={('name', 'course')},
        ),
    ]
